version: '3.3'

services:
  dev:
    image: ros2_jjy0923:humble-desktop-full
    build:
      context: ../
      dockerfile: ./docker/ros2_desktop_full.Dockerfile 
    tty: true 
    container_name: ros2_humble_jjy
    network_mode: host
    privileged: true
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - ../:/ros2_study
      - ~/.ros/:/root/.ros
      - /tmp/.X11-unix/:/tmp/.X11-unix
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /dev:/dev
    command: bash -c "/bin/bash"

